apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: senddensity-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: senddensity

  template:
    metadata:
      labels:
        io.kompose.service: senddensity
      name: senddensity

    spec:
      containers:
        - image: vivian94/walkability:density-v1
          name: senddensity
          resources:
            limits:
              cpu: 300m
          volumeMounts:
            - mountPath: /app/src/main/java/org/mccaughey/output/
              name: sendpolygon-hostpath0
            - mountPath: /root/.m2
              name: sendpolygon-hostpath1

      restartPolicy: Always
      volumes:
        - hostPath:
            path:  /mnt/sharedfolder/output
          name: sendpolygon-hostpath0
        - hostPath:
            path:  /home/ubuntu/.m2
          name: sendpolygon-hostpath1

