apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sendzscore
  name: sendzscore
spec:
  containers:
  - image: vivian94/walkability100v2:sendzscore
    name: sendzscore
    volumeMounts:
    - mountPath: /app/src/main/java/org/mccaughey/output/
      name: sendzscore-hostpath0
    - mountPath: /root/.m2
      name: sendzscore-hostpath1
  restartPolicy: OnFailure
  volumes:
  - hostPath:
      path: /mnt/sharedfolder/output
    name: sendzscore-hostpath0
  - hostPath:
      path: /home/ubuntu/.m2
    name: sendzscore-hostpath1
status: {}
