apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sendpolygon-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sendpolygon

  template:
    metadata:
      labels:
        io.kompose.service: sendpolygon
      name: sendpolygon

    spec:
      containers:
        - image: vivian94/walkability100v2:sendpolygon
          name: sendpolygon
          resources:
            limits:
              cpu: 600m
          volumeMounts:
            - mountPath: /app/src/main/java/org/mccaughey/output/
              name: sendpolygon-hostpath0
            - mountPath: /root/.m2
              name: sendpolygon-hostpath1

      restartPolicy: Always
      volumes:
        - hostPath:
            path:  /mnt/sharedfolder/output
          name: sendpolygon-hostpath0
        - hostPath:
            path:  /home/ubuntu/.m2
          name: sendpolygon-hostpath1

