apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sendpoints
  name: sendpoints
spec:
  containers:
  - image: vivian94/walkability100v2:sendpoints
    name: sendpoints
    volumeMounts:
    - mountPath: /app/src/main/java/org/mccaughey/output/
      name: sendpoints-hostpath0
    - mountPath: /root/.m2
      name: sendpoints-hostpath1
  restartPolicy: OnFailure
  volumes:
  - hostPath:
      path: /mnt/sharedfolder/output
    name: sendpoints-hostpath0
  - hostPath:
      path: /home/ubuntu/.m2
    name: sendpoints-hostpath1
status: {}
